export const UPDATE_FORM_DATA = 'UPDATE_FORM_DATA';
export const SET_ERRORS = 'SET_ERRORS';
export const SET_TABLE_DATA = 'SET_TABLE_DATA';
export const SET_ERROR = 'SET_ERROR';
export const TOGGLE_INCLUDE_COST = 'TOGGLE_INCLUDE_COST';

export default {
    UPDATE_FORM_DATA,
    SET_ERRORS,
    SET_TABLE_DATA,
    SET_ERROR,
    TOGGLE_INCLUDE_COST
}